# This is the config file for Uncraft.
# This config was generated for version 1.1


# GENERAL

# whether to use the whitelist or the blacklist
# true: only allow uncrafting for items on the whitelist
# false: allow uncrafting for every item that is not on the blacklist
use-whitelist: false



# list of items that are allowed to be uncrafted
# check spigot docs for a list of all item identifiers: https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/Material.html
# !!! only relevant if use-whitelist is true !!!
whitelist:
  -

# Uncomment the following list to add all tools and armor to the whitelist

#  - WOODEN_SWORD
#  - DIAMOND_SWORD
#  - IRON_SWORD
#  - GOLDEN_SWORD
#  - NETHERITE_SWORD
#  - STONE_SWORD
#  - WOODEN_AXE
#  - STONE_AXE
#  - DIAMOND_AXE
#  - GOLDEN_AXE
#  - IRON_AXE
#  - TRIDENT
#  - WOODEN_HOE
#  - STONE_HOE
#  - DIAMOND_HOE
#  - NETHERITE_HOE
#  - GOLDEN_HOE
#  - IRON_HOE
#  - IRON_PICKAXE
#  - WOODEN_PICKAXE
#  - GOLDEN_PICKAXE
#  - DIAMOND_PICKAXE
#  - STONE_PICKAXE
#  - NETHERITE_PICKAXE
#  - NETHERITE_SHOVEL
#  - DIAMOND_SHOVEL
#  - IRON_SHOVEL
#  - STONE_SHOVEL
#  - GOLDEN_SHOVEL
#  - WOODEN_SHOVEL
#  - IRON_BOOTS
#  - DIAMOND_BOOTS
#  - LEATHER_BOOTS
#  - NETHERITE_BOOTS
#  - GOLDEN_BOOTS
#  - CHAINMAIL_BOOTS
#  - DIAMOND_LEGGINGS
#  - GOLDEN_LEGGINGS
#  - LEATHER_LEGGINGS
#  - IRON_LEGGINGS
#  - NETHERITE_LEGGINGS
#  - CHAINMAIL_LEGGINGS
#  - IRON_CHESTPLATE
#  - LEATHER_CHESTPLATE
#  - DIAMOND_CHESTPLATE
#  - GOLDEN_CHESTPLATE
#  - CHAINMAIL_CHESTPLATE
#  - LEATHER_HELMET
#  - TURTLE_HELMET
#  - IRON_HELMET
#  - DIAMOND_HELMET
#  - GOLDEN_HELMET
#  - CHAINMAIL_HELMET


# list of items that are NOT allowed to be uncrafted
# check spigot docs for a list of all item identifiers: https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/Material.html
# !!! only relevant if use-whitelist is false !!!
blacklist:
  -





# ADMIN

# announce new updates of Uncraft in the server log
update-check: true