name: Uncraft
version: 1.1
main: de.stamme.uncraft.main.Uncraft
description: Let's Players uncraft items

author: Tonnanto & Fixel
api-version: "1.16"

commands:
  uncraft:
    description: Uncraft the item in your hand.
    usage: /<command> [detail]